# Generated by Django 5.1.1 on 2026-01-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created",
            new_name="created_at",
        ),
    ]
