# Generated by Django 5.1.1 on 2026-01-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"),
        ),
    ]
