# Generated by Django 5.1.1 on 2026-01-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_category_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
    ]
